apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: my-app
type: Opaque
stringData:
  POSTGRES_DB: mydb
  POSTGRES_USER: kogo
  POSTGRES_PASSWORD: math1106

  DBNAME: mydb
  DBUSER: kogo
  DBPASSWORD: math1106
  DBHOST: db
  DBPORT: "5432"

  DJANGO_SECRET_KEY: django-insecure-em3h17zt8o%!b8!abm*n@lem589l!lkarmx&j@9)@dza@p#x#k
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,13.125.245.12"
  CORS_ALLOWED_ORIGINS: "http://localhost,http://127.0.0.1,http://13.125.245.12"

  NEXT_PUBLIC_API_BASE_URL: "/api"
