apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: my-app
type: Opaque
stringData:
  # ==========================
  # Postgres
  # ==========================
  POSTGRES_DB: mydb
  POSTGRES_USER: kogo
  POSTGRES_PASSWORD: math1106
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"

  # ==========================
  # Django
  # ==========================
  DJANGO_SECRET_KEY: "replace-this-with-strong-secret-key"
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "*"
